# Integrating All the data

Importing libraries

In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Readinf the data set

In [129]:
root_path_happiness = 'Cleaned_data/happiness_data_sets'
life_expectancy_df = pd.read_csv("Cleaned_data/Life Expectancy Data.csv")
df_250_Country_Data = pd.read_csv('Cleaned_data/250 Country Data.csv')
df_happinies_2015 = pd.read_csv(root_path_happiness + '/2015.csv')
df_happinies_2016 = pd.read_csv(root_path_happiness + '/2016.csv')
df_happinies_2017 = pd.read_csv(root_path_happiness + '/2017.csv')
df_happinies_2018 = pd.read_csv(root_path_happiness + '/2018.csv')
df_happinies_2019 = pd.read_csv(root_path_happiness + '/2019.csv')

adding a year column for each data set to prepare it for the integration

In [130]:
last_column_2015 = len(df_happinies_2015)*[2015]
last_column_2016 = len(df_happinies_2016)*[2016]
last_column_2017 = len(df_happinies_2017)*[2017]
last_column_2018 = len(df_happinies_2018)*[2018]
last_column_2019 = len(df_happinies_2019)*[2019]
df_Years_2015 = pd.DataFrame({'Year': last_column_2015})
df_Years_2016 = pd.DataFrame({'Year': last_column_2016})
df_Years_2017 = pd.DataFrame({'Year': last_column_2017})
df_Years_2018= pd.DataFrame({'Year': last_column_2018})
df_Years_2019 = pd.DataFrame({'Year': last_column_2019})

In [131]:
df_happinies_2015=pd.concat([df_happinies_2015, df_Years_2015],axis=1)

In [132]:
df_happinies_2016=pd.concat([df_happinies_2016, df_Years_2016],axis=1)

In [133]:
df_happinies_2017_WithLastColumn=pd.concat([df_happinies_2017, df_Years_2017],axis=1)

In [134]:
df_happinies_2018_WithLastColumn =pd.concat([df_happinies_2018, df_Years_2018],axis=1)

In [135]:
df_happinies_2019_WithLastColumn=pd.concat([df_happinies_2019, df_Years_2019],axis=1)
df_happinies_2019

,Unnamed: 0,Happiness Rank,Country,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Trust (Government Corruption),Cluster
0,0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2
1,1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2
2,2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2
3,3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2
4,4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2
...,...,...,...,...,...,...,...,...,...,...,...
151,151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,0
152,152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,0
153,153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,0
154,154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,0
155,155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091,0

Integration the  years happiness datasets

In [136]:
df_happinies_2019 = pd.merge(df_happinies_2019_WithLastColumn,df_happinies_2015[['Region','Country']], on = "Country")
df_happinies_2018 = pd.merge(df_happinies_2018_WithLastColumn,df_happinies_2015[['Region','Country']], on = "Country")
df_happinies_2017 = pd.merge(df_happinies_2017_WithLastColumn,df_happinies_2015[['Region','Country']], on = "Country")


Integrated_Happiness = pd.concat([(pd.concat([(pd.concat([(pd.concat([df_happinies_2015[['Region','Country',"Happiness Rank",
                                "Happiness Score","Economy (GDP per Capita)","Social support","Healthy life expectancy",
                                "Freedom to make life choices","Trust (Government Corruption)","Generosity","Cluster","Year"]], df_happinies_2016[['Region','Country',"Happiness Rank",
                                "Happiness Score","Economy (GDP per Capita)","Social support","Healthy life expectancy",
                                "Freedom to make life choices","Trust (Government Corruption)","Generosity","Cluster","Year"]]], axis=0)),
                                   df_happinies_2017[['Region','Country',"Happiness Rank",
                                "Happiness Score","Economy (GDP per Capita)","Social support","Healthy life expectancy",
                                "Freedom to make life choices","Trust (Government Corruption)","Generosity","Cluster","Year"]]], axis = 0)),
           df_happinies_2018[['Region','Country',"Happiness Rank",
                                "Happiness Score","Economy (GDP per Capita)","Social support","Healthy life expectancy",
                                "Freedom to make life choices","Trust (Government Corruption)","Generosity","Cluster","Year"]]], axis = 0)),
                df_happinies_2019[['Region','Country',"Happiness Rank",
                                "Happiness Score","Economy (GDP per Capita)","Social support","Healthy life expectancy",
                                "Freedom to make life choices","Trust (Government Corruption)","Generosity","Cluster","Year"]]], axis = 0)
Integrated_Happiness.reset_index(inplace=True)
Integrated_Happiness

,index,Region,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Trust (Government Corruption),Generosity,Cluster,Year
0,0,Western Europe,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2,2015
1,1,Western Europe,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2,2015
2,2,Western Europe,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2,2015
3,3,Western Europe,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2,2015
4,4,North America,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
758,144,Middle East and Northern Africa,Yemen,151,3.380,0.28700,1.16300,0.46300,0.14300,0.07700,0.10800,0,2019
759,145,Sub-Saharan Africa,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,0,2019
760,146,Sub-Saharan Africa,Tanzania,153,3.231,0.47600,0.88500,0.49900,0.41700,0.14700,0.27600,0,2019
761,147,Southern Asia,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,0,2019
762,148,Sub-Saharan Africa,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,0,2019

Integrating the 5 years happiness datasets with the country dataset

In [137]:
Inegrated_data = pd.merge(Integrated_Happiness, df_250_Country_Data,left_on="Country", right_on="name", how='left')
Inegrated_data.drop(columns=["Unnamed: 0"],inplace = True)
Inegrated_data.drop(columns=["Unnamed: 0.1"],inplace = True)
Inegrated_data.drop(columns=["Region"],inplace = True)
Inegrated_data.drop(columns=["name"],inplace = True)
Inegrated_data=Inegrated_data[~Inegrated_data['region'].isnull()]
print(Inegrated_data.isnull().sum())
Inegrated_data

index                            0
Country                          0
Happiness Rank                   0
Happiness Score                  0
Economy (GDP per Capita)         0
Social support                   0
Healthy life expectancy          0
Freedom to make life choices     0
Trust (Government Corruption)    0
Generosity                       0
Cluster                          0
Year                             0
region                           0
subregion                        0
population                       0
area                             0
dtype: int64

,index,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Trust (Government Corruption),Generosity,Cluster,Year,region,subregion,population,area
0,0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2,2015,Europe,Western Europe,8341600.0,41284.0
1,1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2,2015,Europe,Northern Europe,334300.0,103000.0
2,2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2,2015,Europe,Northern Europe,5717014.0,43094.0
3,3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2,2015,Europe,Northern Europe,5223256.0,323802.0
4,4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2,2015,Americas,Northern America,36155487.0,9984670.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,143,Malawi,150,3.410,0.19100,0.56000,0.49500,0.44300,0.08900,0.21800,0,2019,Africa,Eastern Africa,16832910.0,118484.0
758,144,Yemen,151,3.380,0.28700,1.16300,0.46300,0.14300,0.07700,0.10800,0,2019,Asia,Western Asia,27478000.0,527968.0
759,145,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,0,2019,Africa,Eastern Africa,11553188.0,26338.0
761,147,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,0,2019,Asia,Southern Asia,27657145.0,652230.0
762,148,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,0,2019,Africa,Middle Africa,4998000.0,622984.0

adding a density column for the integrated dataset as an engineered feature

In [138]:
Inegrated_data["density"] = Inegrated_data["population"]/Inegrated_data["area"]

finding the min, max of the density to discritize the density column

In [139]:
minvalue = Inegrated_data['density'].min()
print(minvalue)

1.9775463362551227

In [140]:
maxvalue = Inegrated_data['density'].max()
print(maxvalue)

7795.774647887324

discritization for the density column

In [141]:
density_group = pd.cut(Inegrated_data.density, [0,400,800,1200,1600,1800,2200,2600,3000,3400,3800,4200,4600,5000,5400,5800,6200,6600,7000,7400,7800],labels=
                       ["0-400" ,"400-800" ,"800-1200" , "1200-1600","1600-2000" , "2000-2400","2400-2800", "2800-3200" , "3200-3600", "3600-4000","4000-4400" ,"4400-4800",
                        "4800-5200" , "5200-5600" ,
                        "5600-6000" ,"6000-6400", "6400-6800", "6800-7200","7200-7600"  , "7600-8000"])
Inegrated_data["density_group"] = density_group 
del Inegrated_data["density"]

In [142]:
Inegrated_data

,index,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Trust (Government Corruption),Generosity,Cluster,Year,region,subregion,population,area,density_group
0,0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2,2015,Europe,Western Europe,8341600.0,41284.0,0-400
1,1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2,2015,Europe,Northern Europe,334300.0,103000.0,0-400
2,2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2,2015,Europe,Northern Europe,5717014.0,43094.0,0-400
3,3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2,2015,Europe,Northern Europe,5223256.0,323802.0,0-400
4,4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2,2015,Americas,Northern America,36155487.0,9984670.0,0-400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,143,Malawi,150,3.410,0.19100,0.56000,0.49500,0.44300,0.08900,0.21800,0,2019,Africa,Eastern Africa,16832910.0,118484.0,0-400
758,144,Yemen,151,3.380,0.28700,1.16300,0.46300,0.14300,0.07700,0.10800,0,2019,Asia,Western Asia,27478000.0,527968.0,0-400
759,145,Rwanda,152,3.334,0.35900,0.71100,0.61400,0.55500,0.41100,0.21700,0,2019,Africa,Eastern Africa,11553188.0,26338.0,400-800
761,147,Afghanistan,154,3.203,0.35000,0.51700,0.36100,0.00000,0.02500,0.15800,0,2019,Asia,Southern Asia,27657145.0,652230.0,0-400
762,148,Central African Republic,155,3.083,0.02600,0.00000,0.10500,0.22500,0.03500,0.23500,0,2019,Africa,Middle Africa,4998000.0,622984.0,0-400

# Exporting data

In [143]:
root_path='Integrated_Data/'
Integrated_Happiness.to_csv("Integrated_Happiness.csv")
Inegrated_data.to_csv("Integrated_Happiness_Country_Data.csv")

# Integration data for Q1

In [144]:
integrated_happiness_df=Integrated_Happiness
life_expectancy_df = life_expectancy_df[['Country', 'Status']]
life_expectancy_df = life_expectancy_df.drop_duplicates()
life_expectancy_df = life_expectancy_df.reset_index()
life_expectancy_df = life_expectancy_df.drop( columns = ['index'], axis = 1)
merged_happiness_life = pd.merge(integrated_happiness_df, life_expectancy_df,left_on="Country", right_on="Country", how='left')
merged_happiness_life.isnull().sum()

index                              0
Region                             0
Country                            0
Happiness Rank                     0
Happiness Score                    0
Economy (GDP per Capita)           0
Social support                     0
Healthy life expectancy            0
Freedom to make life choices       0
Trust (Government Corruption)      0
Generosity                         0
Cluster                            0
Year                               0
Status                           107
dtype: int64

In [145]:
status_nulls=merged_happiness_life[merged_happiness_life['Status'].isnull()]
status_nulls['Country'].unique()
countries = status_nulls['Country']
countries = countries.drop_duplicates()
countries = countries.reset_index()

In [146]:
non_developed = status_nulls.loc[status_nulls['Country'] == "Venezuela"]
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Bolivia"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Vietnam"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Somaliland region"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Macedonia"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Laos"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Palestinian Territories"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Congo (Kinshasa)"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Congo (Brazzaville)"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Ivory Coast"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Tanzania"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Syria"])
non_developed = non_developed.append(status_nulls.loc[status_nulls['Country'] == "Somaliland Region"])
non_developed.replace(np.nan,"Developing" , inplace=True)
non_developed = non_developed.reset_index()

In [147]:
developed = status_nulls.loc[status_nulls['Country'] == "United States"]
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "United Kingdom"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Czech Republic"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "South Korea"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "United Kingdom"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Russia"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "North Cyprus"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Kosovo"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Hong Kong"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Iran"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Puerto Rico"])
developed = developed.append(status_nulls.loc[status_nulls['Country'] == "Taiwan"])
developed.replace(np.nan,"Developed" , inplace=True)
developed = developed.reset_index()

In [148]:
developed_and_non_developed = developed
developed_and_non_developed = developed_and_non_developed.append(non_developed)
developed_and_non_developed = developed_and_non_developed.drop(columns = ["level_0", "index"], axis = 1)
developed_and_non_developed = developed_and_non_developed.reset_index(drop=True)
developed_and_non_developed

,Region,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Trust (Government Corruption),Generosity,Cluster,Year,Status
0,North America,United States,15,7.119,1.394510,1.247110,0.861790,0.546040,0.158900,0.401050,2,2015,Developed
1,North America,United States,13,7.104,1.507960,1.047820,0.779000,0.481630,0.148680,0.410770,2,2016,Developed
2,North America,United States,14,6.993,1.546259,1.419921,0.774287,0.505741,0.135639,0.392579,2,2017,Developed
3,North America,United States,18,6.886,1.398000,1.471000,0.819000,0.547000,0.133000,0.291000,2,2018,Developed
4,North America,United States,19,6.892,1.433000,1.457000,0.874000,0.454000,0.128000,0.280000,2,2019,Developed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,Middle East and Northern Africa,Syria,156,3.069,0.747190,0.148660,0.629940,0.069120,0.172330,0.483970,0,2016,Developing
103,Middle East and Northern Africa,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1,2017,Developing
104,Middle East and Northern Africa,Syria,150,3.462,0.689000,0.382000,0.539000,0.088000,0.144000,0.376000,1,2018,Developing
105,Middle East and Northern Africa,Syria,149,3.462,0.619000,0.378000,0.440000,0.013000,0.141000,0.331000,0,2019,Developing
106,Sub-Saharan Africa,Somaliland Region,97,5.057,0.255580,0.758620,0.331080,0.391300,0.367940,0.514790,1,2016,Developing

In [149]:
for index, row in countries.iterrows():
  merged_happiness_life = merged_happiness_life[merged_happiness_life["Country"] != row["Country"]]

In [150]:
merged_happiness_life = merged_happiness_life.append(developed_and_non_developed)
merged_happiness_life = merged_happiness_life.reset_index(drop=True)
merged_happiness_life = merged_happiness_life.reset_index(drop=True)

In [151]:
merged_happiness_life.isnull().sum()

index                            107
Region                             0
Country                            0
Happiness Rank                     0
Happiness Score                    0
Economy (GDP per Capita)           0
Social support                     0
Healthy life expectancy            0
Freedom to make life choices       0
Trust (Government Corruption)      0
Generosity                         0
Cluster                            0
Year                               0
Status                             0
dtype: int64

In [152]:
merged_happiness_life

,index,Region,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Healthy life expectancy,Freedom to make life choices,Trust (Government Corruption),Generosity,Cluster,Year,Status
0,0.0,Western Europe,Switzerland,1,7.587,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2,2015,Developed
1,1.0,Western Europe,Iceland,2,7.561,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2,2015,Developed
2,2.0,Western Europe,Denmark,3,7.527,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2,2015,Developed
3,3.0,Western Europe,Norway,4,7.522,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2,2015,Developed
4,4.0,North America,Canada,5,7.427,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2,2015,Developed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
758,NaN,Middle East and Northern Africa,Syria,156,3.069,0.747190,0.148660,0.629940,0.069120,0.172330,0.483970,0,2016,Developing
759,NaN,Middle East and Northern Africa,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1,2017,Developing
760,NaN,Middle East and Northern Africa,Syria,150,3.462,0.689000,0.382000,0.539000,0.088000,0.144000,0.376000,1,2018,Developing
761,NaN,Middle East and Northern Africa,Syria,149,3.462,0.619000,0.378000,0.440000,0.013000,0.141000,0.331000,0,2019,Developing
762,NaN,Sub-Saharan Africa,Somaliland Region,97,5.057,0.255580,0.758620,0.331080,0.391300,0.367940,0.514790,1,2016,Developing

# Exporting data

In [155]:
root_path='Integrated_Data/'
merged_happiness_life.to_csv(root_path+"Q1_Integrated_Happiness_with_life.csv")

# Q5 data

In [156]:
root_path='Integrated_Data/'
df_happinies_2019.to_csv(root_path+"Q5_df_happinies_2019_with_Region.csv")
df_happinies_2018.to_csv(root_path+"Q5_df_happinies_2018_with_Region.csv")
df_happinies_2017.to_csv(root_path+"Q5_df_happinies_2017_with_Region.csv")